
# Stage 3: Server (Node.js)
FROM node:22.7-alpine@sha256:ed9736a13b88ba55cbc08c75c9edac8ae7f72840482e40324670b299336680c1 AS server
WORKDIR /usr/src/app

COPY package*.json ./

# socat, tsx
#RUN apk add --no-cache socat=1.8.0.0-r0
RUN npm ci --ignore-scripts
#RUN npm install --save-dev tsx@4.19.3

# COPY test.sh .

# ENTRYPOINT ["./test.sh"]
#CMD ["socat", "-dddd", "-", "VSOCK-CONNECT:3:1080"]
CMD ["tsx"]
